# docker-compose.yml
version: '3.9'

services:
  web:
    build: ./
    restart: always
    command: sh ./bin/start_gunicorn.prod.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3030:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  pg_data: