from django.urls import path
from api.v1.admin.views import *

urlpatterns = [
    path('menu/create/', MenuCreateView.as_view()),
    path('menu/<int:id>/', MenuEditView.as_view()),
    path('menu/<int:id>/posts/', PostByMenuView.as_view()),
    path('menu/<int:id>/gallery/', GalleryByMenuView.as_view()),
    path('post/create/', PostCreateView.as_view()),
    path('post/<int:id>/', PostEditView.as_view()),
    path('gallery/create/', GalleryCreateView.as_view()),
    path('gallery/<int:id>/', GalleryEditView.as_view()),
    path('gallery/file/create/', GalleryFileCreateView.as_view()),
    path('gallery/file/<int:id>/', GalleryFileRetrieveDestroyView.as_view()),
    path('course/create/', CourseCreateView.as_view()),
    path('course/<int:id>/', CourseEditView.as_view()),
    path('course/file/create/', CourseFileCreateView.as_view()),
    path('course/file/<int:id>/', CourseFileRetrieveDestroyView.as_view()),
    path('program/<int:id>/info-content/', InfoContentByProgramView.as_view()),
    path('program/<int:id>/question/', QuestionListByProgramView.as_view()),
    path('program/<int:id>/gallery/', GalleryByProgramView.as_view()),
    path('program/<int:id>/posts/', PostListByProgramView.as_view()),
    path('program/create/', ProgramCreateView.as_view()),
    path('program/<int:id>/', ProgramEditView.as_view()),
    path('teacher/create/', TeacherCreateView.as_view()),
    path('teacher/<int:id>/', TeacherEditView.as_view()),
    path('feedback/create/', FeedbackCreateView.as_view()),
    path('feedback/<int:id>/', FeedbackEditView.as_view()),
    path('subscriptionrequest/create/', SubscriptionRequestCreateView.as_view()),
    path('subscriptionrequest/<int:id>/', SubscriptionRequestEditView.as_view()),
    path('companies/', CompanyCreateView.as_view()),
    path('companies/<int:id>/', CompanyEditView.as_view()),
    path('course/<int:id>/programs/', ProgramListByCourseView.as_view()),
    path('course/<int:id>/teachers/', TeacherListByCourseView.as_view()),
    path('course/<int:id>/information/', InformationContentByCourseView.as_view()),
    path('course/information/', InformationContentCreateView.as_view()),
    path('course/information/<int:id>/', InformationContentEditView.as_view()),
    path('course/info-details/', InformationContentDetailCreateView.as_view()),
    path('course/info-details/<int:id>/', InformationContentDetailEditView.as_view()),
    path('course/<int:id>/cost-educations/', CostEducationListByCourseView.as_view()),
    path('course/cost-education/', CostEducationCreateView.as_view()),
    path('course/cost-education/<int:id>/', CostEducationEditView.as_view()),
    path('course/<int:id>/certificate/', CertificateByCourseView.as_view()),
    path('course/certificate/', CertificateCreateView.as_view()),
    path('course/certificate/<int:id>/', CertificateEditView.as_view()),
    path('course/<int:id>/program-training/', QuestionAndAnswersListByCourseView.as_view()),
    path('course/program-training/', QuestionAndAnswersCreateView.as_view()),
    path('course/program-training/<int:id>/', QuestionAndAnswersEditView.as_view()),
    path('course/<int:id>/results/', ResultListByCourseView.as_view()),
    path('course/result/', ResultCreateView.as_view()),
    path('course/result/<int:id>/', ResultEditView.as_view()),
]
