# Generated by Django 3.2.4 on 2021-06-21 07:48

from django.db import migrations, models
import django.db.models.deletion
import user.services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='file',
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery/', validators=[user.services.validators.validate_file_type_gallery])),
                ('is_active', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_files', to='user.gallery')),
            ],
        ),
    ]
