# Generated by Django 3.2.4 on 2021-06-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210621_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='author',
        ),
    ]
