# Generated by Django 3.2.4 on 2021-06-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_gallery_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryfile',
            name='is_active',
        ),
    ]
